export const top_brands_data = [
    {
        id: 1,
        name: "La Pino's Pizza",
        image: "https://nikunjsonigara.github.io/Food-Delivery-App-PT/image/Ellipse%201%20(1).png",
        description: "Pizza, Fast Food, Beverages",
        address: "Vesu, Surat",
        time: "11am - 11pm",
        average_cost: "700rs per 2 person",
        location: "https://www.google.com/maps/place/La+Pino'z+Pizza/@21.1475147,72.7628954,17z/data=!3m2!4b1!5s0x3be04d877f31bd7f:0x8538a10f9c5dfdc9!4m6!3m5!1s0x3be04d877a1c6bb5:0x94d7f84db7ecdc60!8m2!3d21.1475097!4d72.7654703!16s%2Fg%2F11fylw5mmw?entry=ttu",
        menu: [
            {
                menu_id: 1,
                menu_name: "dinning menu",
                menu_image: "https://d4t7t8y8xqo0t.cloudfront.net/resized/1080X/restaurant%2F669514%2Fmenu%2Fmenu11575107650803.jpg",
            },
            {
                menu_id: 2,
                menu_name: "takeaway menu",
                menu_image: "https://10619-2.s.cdn12.com/m0/Ahmedabad-La-Pinoz-Pizza-menu.jpg",
            },
        ],
        food: [
            {
                title: "Recommended",
                food_items: [
                    {
                        id: "lp1",
                        name: "Margherita Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "140",
                        food_type: "Pizza",
                        popular: true,
                        time: "20min",
                        image: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?q=80&w=2235&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp4",
                        name: "Double Cheese Margherita Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "150",
                        food_type: "Pizza",
                        popular: true,
                        time: "20min",
                        image: "https://images.unsplash.com/photo-1571066811602-716837d681de?q=80&w=1844&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp6",
                        name: "Garden Delight Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "180",
                        food_type: "Pizza",
                        popular: true,
                        time: "20min",
                        image: "https://images.unsplash.com/photo-1593504049359-74330189a345?q=80&w=2127&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp7",
                        name: "Lovers Bite Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "200",
                        food_type: "Pizza",
                        popular: true,
                        time: "20min",
                        image: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?q=80&w=2340&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                ]
            },
            {
                title: "Pizzas",
                food_items: [
                    {
                        id: "lp1",
                        name: "Margherita Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "140",
                        food_type: "Pizza",
                        popular: true,
                        time: "20min",
                        image: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?q=80&w=2235&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp2",
                        name: "Brick Oven Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "150",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?q=80&w=2188&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp3",
                        name: "Italian Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "130",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1544982503-9f984c14501a?q=80&w=2187&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp4",
                        name: "Double Cheese Margherita Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "150",
                        food_type: "Pizza",
                        popular: true,
                        time: "20min",
                        image: "https://images.unsplash.com/photo-1571066811602-716837d681de?q=80&w=1844&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp5",
                        name: "Neapolitan Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "160",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1593246049226-ded77bf90326?q=80&w=2235&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp6",
                        name: "Garden Delight Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "180",
                        food_type: "Pizza",
                        popular: true,
                        time: "20min",
                        image: "https://images.unsplash.com/photo-1593504049359-74330189a345?q=80&w=2127&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp7",
                        name: "Lovers Bite Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "200",
                        food_type: "Pizza",
                        popular: true,
                        time: "20min",
                        image: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?q=80&w=2340&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp8",
                        name: "Sicilian Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "210",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1581873372796-635b67ca2008?q=80&w=2340&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp9",
                        name: "New York Style Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "220",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1552539618-7eec9b4d1796?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MjV8fHxlbnwwfHx8fHw%3D",
                    },
                    {
                        id: "lp10",
                        name: "California Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "250",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1595708684082-a173bb3a06c5?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8Mjh8fHxlbnwwfHx8fHw%3D",
                    },
                    {
                        id: "lp11",
                        name: "Greek Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "300",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=2338&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                ]
            },
            {
                title: "Classic Pizzas For Classic Maniacs",
                food_items: [
                    {
                        id: "lp2",
                        name: "Brick Oven Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "150",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?q=80&w=2188&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp4",
                        name: "Double Cheese Margherita Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "150",
                        food_type: "Pizza",
                        popular: true,
                        time: "20min",
                        image: "https://images.unsplash.com/photo-1571066811602-716837d681de?q=80&w=1844&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp5",
                        name: "Neapolitan Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "160",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1593246049226-ded77bf90326?q=80&w=2235&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp7",
                        name: "Lovers Bite Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "200",
                        food_type: "Pizza",
                        popular: true,
                        time: "20min",
                        image: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?q=80&w=2340&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp9",
                        name: "New York Style Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "220",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1552539618-7eec9b4d1796?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MjV8fHxlbnwwfHx8fHw%3D",
                    },
                    {
                        id: "lp10",
                        name: "California Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "250",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1595708684082-a173bb3a06c5?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8Mjh8fHxlbnwwfHx8fHw%3D",
                    },
                    {
                        id: "lp11",
                        name: "Greek Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "300",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=2338&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                ]
            },
            {
                title: "Garlic Breads",
                food_items: [
                    {
                        id: "lp2",
                        name: "Brick Oven Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "150",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?q=80&w=2188&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp5",
                        name: "Neapolitan Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "160",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1593246049226-ded77bf90326?q=80&w=2235&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp9",
                        name: "New York Style Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "220",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1552539618-7eec9b4d1796?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MjV8fHxlbnwwfHx8fHw%3D",
                    },
                    {
                        id: "lp11",
                        name: "Greek Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "300",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=2338&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                ]
            },
            {
                title: "Lasagna",
                food_items: [
                    {
                        id: "lp2",
                        name: "Brick Oven Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "150",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?q=80&w=2188&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp9",
                        name: "New York Style Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "220",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1552539618-7eec9b4d1796?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MjV8fHxlbnwwfHx8fHw%3D",
                    },
                    {
                        id: "lp11",
                        name: "Greek Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "300",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=2338&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                ]
            },
            {
                title: "Desserts",
                food_items: [
                    {
                        id: "lp5",
                        name: "Neapolitan Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "160",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1593246049226-ded77bf90326?q=80&w=2235&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp11",
                        name: "Greek Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "300",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=2338&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                ]
            }
        ]
    },
    {
        id: 2,
        name: "McDonald's",
        image: "https://nikunjsonigara.github.io/Food-Delivery-App-PT/image/Ellipse%202%20(1).png",
        description: "Pizza, Fast Food, Beverages",
        address: "Vesu, Surat",
        time: "11am - 11pm",
        average_cost: "700rs per 2 person",
        location: "https://www.google.com/maps/place/La+Pino'z+Pizza/@21.1475147,72.7628954,17z/data=!3m2!4b1!5s0x3be04d877f31bd7f:0x8538a10f9c5dfdc9!4m6!3m5!1s0x3be04d877a1c6bb5:0x94d7f84db7ecdc60!8m2!3d21.1475097!4d72.7654703!16s%2Fg%2F11fylw5mmw?entry=ttu",
        menu: [
            {
                menu_id: 1,
                menu_name: "dinning menu",
                menu_image: "https://b.zmtcdn.com/data/menus/271/110271/26e5d86e31b47a596145265884ff35c1.jpg",
            },
            {
                menu_id: 2,
                menu_name: "takeaway menu",
                menu_image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgFBH-3U_PL80Y9iUYA1JupGitGweDptHGUvWaS6PfTg&s",
            },
        ],
        food: [
            {
                title: "Recommended",
                food_items: [
                    {
                        id: "mc1",
                        name: "Chicken Burger",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "140",
                        food_type: "Burger",
                        popular: true,
                        time: "15min",
                        image: "https://plus.unsplash.com/premium_photo-1683655058728-415f4f2674bf?q=80&w=2187&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "mc4",
                        name: "McFlurry® with OREO® Cookies",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "220",
                        food_type: "Sweets",
                        popular: true,
                        time: "5min",
                        image: "https://s7d1.scene7.com/is/image/mcdonalds/DC_202002_3832_OREOMcFlurry_832x472:nutrition-calculator-tile",
                    },
                    {
                        id: "mc6",
                        name: "Spicy McCrispy",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "180",
                        food_type: "Burger",
                        popular: true,
                        time: "18min",
                        image: "https://s7d1.scene7.com/is/image/mcdonalds/DC_202012_0116_SpicyCrispyChicken_PotatoBun_832x472:nutrition-calculator-tile",
                    },
                    {
                        id: "mc8",
                        name: "Big Mac",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "200",
                        food_type: "Burger",
                        popular: false,
                        time: "10min",
                        image: "https://s7d1.scene7.com/is/image/mcdonalds/Header_BigMac_832x472:nutrition-calculator-tile",
                    },
                ]
            },
            {
                title: "Burgers",
                food_items: [
                    {
                        id: "mc1",
                        name: "Chicken Burger",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "140",
                        food_type: "Burger",
                        popular: true,
                        time: "15min",
                        image: "https://plus.unsplash.com/premium_photo-1683655058728-415f4f2674bf?q=80&w=2187&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "mc2",
                        name: "Chicken McNuggets",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "150",
                        food_type: "Burger",
                        popular: false,
                        time: "25min",
                        image: "https://s7d1.scene7.com/is/image/mcdonalds/DC_202006_0483_4McNuggets_Stacked_832x472:nutrition-calculator-tile",
                    },
                    {
                        id: "mc3",
                        name: "Quarter Pounder® with Cheese",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "130",
                        food_type: "Burger",
                        popular: false,
                        time: "14min",
                        image: "https://s7d1.scene7.com/is/image/mcdonalds/DC_202201_0007-005_QuarterPounderwithCheese_832x472:nutrition-calculator-tile",
                    },
                    {
                        id: "mc5",
                        name: "Egg McMuffin",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "160",
                        food_type: "Burger",
                        popular: false,
                        time: "17min",
                        image: "https://s7d1.scene7.com/is/image/mcdonalds/DC_202004_0046_EggMcMuffin_832x472:nutrition-calculator-tile",
                    },
                    {
                        id: "mc6",
                        name: "Spicy McCrispy",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "180",
                        food_type: "Burger",
                        popular: true,
                        time: "18min",
                        image: "https://s7d1.scene7.com/is/image/mcdonalds/DC_202012_0116_SpicyCrispyChicken_PotatoBun_832x472:nutrition-calculator-tile",
                    },
                    {
                        id: "mc7",
                        name: "Hamburger: The Classic McDonald's Burger",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "200",
                        food_type: "Burger",
                        popular: false,
                        time: "20min",
                        image: "https://s7d1.scene7.com/is/image/mcdonalds/Header_Hamburger_832x472:nutrition-calculator-tile",
                    },
                    {
                        id: "mc8",
                        name: "Big Mac",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "200",
                        food_type: "Burger",
                        popular: false,
                        time: "10min",
                        image: "https://s7d1.scene7.com/is/image/mcdonalds/Header_BigMac_832x472:nutrition-calculator-tile",
                    },
                ]
            },
            {
                title: "Sweets",
                food_items: [
                    {
                        id: "mc4",
                        name: "McFlurry® with OREO® Cookies",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "220",
                        food_type: "Sweets",
                        popular: true,
                        time: "5min",
                        image: "https://s7d1.scene7.com/is/image/mcdonalds/DC_202002_3832_OREOMcFlurry_832x472:nutrition-calculator-tile",
                    },
                    {
                        id: "mc9",
                        name: "McFlurry® with M&M'S® Candies",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "150",
                        food_type: "Sweets",
                        popular: true,
                        time: "20min",
                        image: "https://s7d1.scene7.com/is/image/mcdonalds/DC_202002_3830_MandMMcFlurry_832x472:nutrition-calculator-tile",
                    },
                    {
                        id: "mc10",
                        name: "Vanilla Cone",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "40",
                        food_type: "Sweets",
                        popular: false,
                        time: "7min",
                        image: "https://s7d1.scene7.com/is/image/mcdonalds/DC_202106_0336_LargeVanillaCone_832x472:nutrition-calculator-tile",
                    },
                    {
                        id: "mc11",
                        name: "Chocolate Shake",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "200",
                        food_type: "Sweets",
                        popular: true,
                        time: "12min",
                        image: "https://s7d1.scene7.com/is/image/mcdonalds/DC_201907_1509_MediumChocolateShake_Glass_A1_832x472:nutrition-calculator-tile",
                    },
                    {
                        id: "mc12",
                        name: "Vanilla Shake",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "220",
                        food_type: "Sweets",
                        popular: false,
                        time: "15min",
                        image: "https://s7d1.scene7.com/is/image/mcdonalds/DC_201907_1598_MediumVanillaShake_Glass_A1_832x472:nutrition-calculator-tile",
                    },
                    {
                        id: "mc13",
                        name: "Strawberry Shake",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "250",
                        food_type: "Sweets",
                        popular: true,
                        time: "21min",
                        image: "https://s7d1.scene7.com/is/image/mcdonalds/DC_201907_1513_MediumStrawberryShake_Glass_A1_832x472:nutrition-calculator-tile",
                    },
                    {
                        id: "mc14",
                        name: "Hot Fudge Sundae",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "280",
                        food_type: "Sweets",
                        popular: true,
                        time: "23min",
                        image: "https://s7d1.scene7.com/is/image/mcdonalds/DC_201907_0337_HotFudgeSundae_832x472:nutrition-calculator-tile",
                    },
                ]
            },
        ]
    },
    {
        id: 3,
        name: "Starbucks",
        image: "https://nikunjsonigara.github.io/Food-Delivery-App-PT/image/Ellipse%203%20(1).png",
        description: "Pizza, Fast Food, Beverages",
        address: "Vesu, Surat",
        time: "11am - 11pm",
        average_cost: "700rs per 2 person",
        location: "https://www.google.com/maps/place/La+Pino'z+Pizza/@21.1475147,72.7628954,17z/data=!3m2!4b1!5s0x3be04d877f31bd7f:0x8538a10f9c5dfdc9!4m6!3m5!1s0x3be04d877a1c6bb5:0x94d7f84db7ecdc60!8m2!3d21.1475097!4d72.7654703!16s%2Fg%2F11fylw5mmw?entry=ttu",
        menu: [
            {
                menu_id: 1,
                menu_name: "dinning menu",
                menu_image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQs0hiEhh3pRiFw6RcTupvwS6UxVdaYymqaC46Z9pxINA&s",
            },
            {
                menu_id: 2,
                menu_name: "takeaway menu",
                menu_image: "https://cheatdaydesign.com/wp-content/uploads/2022/09/Starbucks-Nutrition-For-Addons.jpg.webp",
            },
        ],
        food: [
            {
                title: "Recommended",
                food_items: [
                    {
                        id: "sb1",
                        name: "Vienna Creamy Latte",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "414",
                        food_type: "Drinks",
                        popular: true,
                        time: "20min",
                        image: "https://starbucks-cdn-01.s3.ap-south-1.amazonaws.com/Items/Large/webP/M114873.webp",
                    },
                    {
                        id: "sb3",
                        name: "Cappuccino",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "283",
                        food_type: "Drinks",
                        popular: false,
                        time: "25min",
                        image: "https://starbucks-cdn-01.s3.ap-south-1.amazonaws.com/Items/Small/100419.jpg",
                    },
                    {
                        id: "sb4",
                        name: "Caramel Macchiato",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "351",
                        food_type: "Drinks",
                        popular: true,
                        time: "20min",
                        image: "https://starbucks-cdn-01.s3.ap-south-1.amazonaws.com/Items/Small/100405.jpg",
                    },
                    {
                        id: "sb7",
                        name: "Flat White",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "200",
                        food_type: "Drinks",
                        popular: true,
                        time: "20min",
                        image: "https://starbucks-cdn-01.s3.ap-south-1.amazonaws.com/Items/Small/103973.jpg",
                    },
                ]
            },
            {
                title: "Drinks",
                food_items: [
                    {
                        id: "sb1",
                        name: "Vienna Creamy Latte",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "414",
                        food_type: "Drinks",
                        popular: true,
                        time: "20min",
                        image: "https://starbucks-cdn-01.s3.ap-south-1.amazonaws.com/Items/Large/webP/M114873.webp",
                    },
                    {
                        id: "lp2",
                        name: "Vienna Creamy Iced Latte",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "456",
                        food_type: "Drinks",
                        popular: false,
                        time: "25min",
                        image: "https://starbucks-cdn-01.s3.ap-south-1.amazonaws.com/Items/Large/webP/M114853.webp",
                    },
                    {
                        id: "sb3",
                        name: "Cappuccino",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "283",
                        food_type: "Drinks",
                        popular: false,
                        time: "25min",
                        image: "https://starbucks-cdn-01.s3.ap-south-1.amazonaws.com/Items/Small/100419.jpg",
                    },
                    {
                        id: "sb4",
                        name: "Caramel Macchiato",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "351",
                        food_type: "Drinks",
                        popular: true,
                        time: "20min",
                        image: "https://starbucks-cdn-01.s3.ap-south-1.amazonaws.com/Items/Small/100405.jpg",
                    },
                    {
                        id: "sb5",
                        name: "Caffe Latte",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "288",
                        food_type: "Drinks",
                        popular: false,
                        time: "25min",
                        image: "https://starbucks-cdn-01.s3.ap-south-1.amazonaws.com/Items/Small/100377.jpg",
                    },
                    {
                        id: "sb6",
                        name: "Caffe Americano",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "180",
                        food_type: "Drinks",
                        popular: true,
                        time: "17min",
                        image: "https://starbucks-cdn-01.s3.ap-south-1.amazonaws.com/Items/Small/100433.jpg",
                    },
                    {
                        id: "sb7",
                        name: "Flat White",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "200",
                        food_type: "Drinks",
                        popular: true,
                        time: "20min",
                        image: "https://starbucks-cdn-01.s3.ap-south-1.amazonaws.com/Items/Small/103973.jpg",
                    },
                    {
                        id: "sb8",
                        name: "Iced Chocolate Cappuccino",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "388",
                        food_type: "Drinks",
                        popular: false,
                        time: "25min",
                        image: "https://starbucks-cdn-01.s3.ap-south-1.amazonaws.com/Items/Small/104072.jpg",
                    },
                ]
            },
        ]
    },
    {
        id: 4,
        name: "Burger King",
        image: "https://nikunjsonigara.github.io/Food-Delivery-App-PT/image/Ellipse%203%20(2).png",
        description: "Pizza, Fast Food, Beverages",
        address: "Vesu, Surat",
        time: "11am - 11pm",
        average_cost: "700rs per 2 person",
        location: "https://www.google.com/maps/place/La+Pino'z+Pizza/@21.1475147,72.7628954,17z/data=!3m2!4b1!5s0x3be04d877f31bd7f:0x8538a10f9c5dfdc9!4m6!3m5!1s0x3be04d877a1c6bb5:0x94d7f84db7ecdc60!8m2!3d21.1475097!4d72.7654703!16s%2Fg%2F11fylw5mmw?entry=ttu",
        menu: [
            {
                menu_id: 1,
                menu_name: "dinning menu",
                menu_image: "https://b.zmtcdn.com/data/menus/981/3200981/f1b7578390b03a9a3f5b5f602c753fe8.jpg",
            },
            {
                menu_id: 2,
                menu_name: "takeaway menu",
                menu_image: "https://i.pinimg.com/736x/61/f2/90/61f290389396673a8fcf0f579e368932.jpg",
            },
        ],
        food: [
            {
                title: "Recommended",
                food_items: [
                    {
                        id: "bk2",
                        name: "Whopper",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "155",
                        food_type: "Burger",
                        popular: false,
                        time: "14min",
                        image: "https://cdn.sanity.io/images/czqk28jt/prod_bk_us/70faefbd88821e96bb3c473df7c57da383b821cb-1333x1333.png?w=1350&q=80&fit=max&auto=format",
                    },
                    {
                        id: "bk3",
                        name: "Impossible™ Whopper",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "135",
                        food_type: "Burger",
                        popular: true,
                        time: "25min",
                        image: "https://cdn.sanity.io/images/czqk28jt/prod_bk_us/5dddf194b6dfd89567d029f2e74829fd6e7e75f8-1333x1333.png?w=1350&q=80&fit=max&auto=format",
                    },
                    {
                        id: "bk9",
                        name: "Soft Serve Cup",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "150",
                        food_type: "Sweets",
                        popular: true,
                        time: "20min",
                        image: "https://cdn.sanity.io/images/czqk28jt/prod_bk_us/8cda806b1dd6922c9364200ec1dad1d525925ce5-1333x1333.png?w=1350&q=80&fit=max&auto=format",
                    },
                    {
                        id: "bk5",
                        name: "Double Whopper",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "172",
                        food_type: "Burger",
                        popular: false,
                        time: "25min",
                        image: "https://cdn.sanity.io/images/czqk28jt/prod_bk_us/dd6b6b5e4d80d07fe74f76ef43cdc489cde70fba-1333x1333.png?w=1350&q=80&fit=max&auto=format",
                    },
                ]
            },
            {
                title: "Burger",
                food_items: [
                    {
                        id: "bk1",
                        name: "Candied Bacon Whopper®",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "145",
                        food_type: "Burger",
                        popular: true,
                        time: "20min",
                        image: "https://cdn.sanity.io/images/czqk28jt/prod_bk_us/b23587c576d65e9c33a306a8d96b3902da5d9262-1333x1333.png?w=1350&q=80&fit=max&auto=format",
                    },
                    {
                        id: "bk2",
                        name: "Whopper",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "155",
                        food_type: "Burger",
                        popular: false,
                        time: "14min",
                        image: "https://cdn.sanity.io/images/czqk28jt/prod_bk_us/70faefbd88821e96bb3c473df7c57da383b821cb-1333x1333.png?w=1350&q=80&fit=max&auto=format",
                    },
                    {
                        id: "bk3",
                        name: "Impossible™ Whopper",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "135",
                        food_type: "Burger",
                        popular: true,
                        time: "25min",
                        image: "https://cdn.sanity.io/images/czqk28jt/prod_bk_us/5dddf194b6dfd89567d029f2e74829fd6e7e75f8-1333x1333.png?w=1350&q=80&fit=max&auto=format",
                    },
                    {
                        id: "bk4",
                        name: "Texas Double Whopper",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "165",
                        food_type: "Burger",
                        popular: true,
                        time: "20min",
                        image: "https://cdn.sanity.io/images/czqk28jt/prod_bk_us/a2b3c1184bec453570c794d192349b4b9dd65cae-1333x1333.png?w=1350&q=80&fit=max&auto=format",
                    },
                    {
                        id: "bk5",
                        name: "Double Whopper",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "172",
                        food_type: "Burger",
                        popular: false,
                        time: "25min",
                        image: "https://cdn.sanity.io/images/czqk28jt/prod_bk_us/dd6b6b5e4d80d07fe74f76ef43cdc489cde70fba-1333x1333.png?w=1350&q=80&fit=max&auto=format",
                    },
                    {
                        id: "bk6",
                        name: "Triple Whopper",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "185",
                        food_type: "Burger",
                        popular: true,
                        time: "20min",
                        image: "https://cdn.sanity.io/images/czqk28jt/prod_bk_us/1c9ed40f7e09c637548141003698988098a64a78-1333x1333.png?w=1350&q=80&fit=max&auto=format",
                    },
                    {
                        id: "bk7",
                        name: "Bacon King",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "210",
                        food_type: "Burger",
                        popular: true,
                        time: "20min",
                        image: "https://cdn.sanity.io/images/czqk28jt/prod_bk_us/63103c51d3c7cf058e0f283f4fe5da2982072994-1333x1333.png?w=1350&q=80&fit=max&auto=format",
                    },
                ]
            },
            {
                title: "Sweets",
                food_items: [
                    {
                        id: "bk8",
                        name: "HERSHEY'S® Sundae Pie",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "160",
                        food_type: "Sweets",
                        popular: false,
                        time: "25min",
                        image: "https://cdn.sanity.io/images/czqk28jt/prod_bk_us/d09c9f0030c3919f066168232356544eb84462b3-1333x1333.png?w=1350&q=80&fit=max&auto=format",
                    },
                    {
                        id: "bk9",
                        name: "Soft Serve Cup",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "150",
                        food_type: "Sweets",
                        popular: true,
                        time: "20min",
                        image: "https://cdn.sanity.io/images/czqk28jt/prod_bk_us/8cda806b1dd6922c9364200ec1dad1d525925ce5-1333x1333.png?w=1350&q=80&fit=max&auto=format",
                    },
                    {
                        id: "bk10",
                        name: "2 Chocolate Chip Cookies",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "160",
                        food_type: "Sweets",
                        popular: false,
                        time: "25min",
                        image: "https://cdn.sanity.io/images/czqk28jt/prod_bk_us/a9511887054bc796a8d1ebd0d8931a84f5793472-1333x1333.png?w=1350&q=80&fit=max&auto=format",
                    },
                ]
            },
        ]
    },
    {
        id: 5,
        name: "KFC",
        image: "https://nikunjsonigara.github.io/Food-Delivery-App-PT/image/Ellipse%204.png",
        description: "Pizza, Fast Food, Beverages",
        address: "Vesu, Surat",
        time: "11am - 11pm",
        average_cost: "700rs per 2 person",
        location: "https://www.google.com/maps/place/La+Pino'z+Pizza/@21.1475147,72.7628954,17z/data=!3m2!4b1!5s0x3be04d877f31bd7f:0x8538a10f9c5dfdc9!4m6!3m5!1s0x3be04d877a1c6bb5:0x94d7f84db7ecdc60!8m2!3d21.1475097!4d72.7654703!16s%2Fg%2F11fylw5mmw?entry=ttu",
        menu: [
            {
                menu_id: 1,
                menu_name: "dinning menu",
                menu_image: "https://d4t7t8y8xqo0t.cloudfront.net/resized/1080X/restaurant%2F652973%2Fmenu%2Fmenu11536652428522.jpg",
            },
            {
                menu_id: 2,
                menu_name: "takeaway menu",
                menu_image: "https://d4t7t8y8xqo0t.cloudfront.net/resized/1080X/group%2F4479%2Fmenu%2Fmenu020181022043047.jpg",
            },
        ],
        food: [
            {
                title: "Recommended",
                food_items: [
                    {
                        id: "kfc3",
                        name: "Popcorn Biryani Combo",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "690",
                        food_type: "Biryani",
                        popular: false,
                        time: "25min",
                        image: "https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/D-PR00002052.jpg?ver=39.7",
                    },
                    {
                        id: "kfc9",
                        name: "Veg Zinger Burger",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "188",
                        food_type: "Burger",
                        popular: false,
                        time: "25min",
                        image: "https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/D-K146.jpg?ver=39.7",
                    },
                    {
                        id: "kfc5",
                        name: "Classic Chicken Biryani Bucket",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "229",
                        food_type: "Biryani",
                        popular: false,
                        time: "25min",
                        image: "https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/D-K623.jpg?ver=39.7",
                    },
                    {
                        id: "kfc6",
                        name: "Veg Biryani Bucket",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "199",
                        food_type: "Biryani",
                        popular: true,
                        time: "20min",
                        image: "https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/D-K622.jpg?ver=39.7",
                    },
                ]
            },
            {
                title: "Biryani",
                food_items: [
                    {
                        id: "kfc1",
                        name: "Classic Biryani Combo",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "740",
                        food_type: "Biryani",
                        popular: true,
                        time: "20min",
                        image: "https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/D-PR00002166.jpg?ver=39.7",
                    },
                    {
                        id: "kfc2",
                        name: "Smoky Grilled Biryani Combo",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "740",
                        food_type: "Biryani",
                        popular: false,
                        time: "25min",
                        image: "https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/D-PR00002017.jpg?ver=39.7",
                    },
                    {
                        id: "kfc3",
                        name: "Popcorn Biryani Combo",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "690",
                        food_type: "Biryani",
                        popular: false,
                        time: "25min",
                        image: "https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/D-PR00002052.jpg?ver=39.7",
                    },
                    {
                        id: "kfc4",
                        name: "Classic Chicken Biryani Bucket (Large)",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "475",
                        food_type: "Biryani",
                        popular: true,
                        time: "20min",
                        image: "https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/D-K626.jpg?ver=39.7",
                    },
                    {
                        id: "kfc5",
                        name: "Classic Chicken Biryani Bucket",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "229",
                        food_type: "Biryani",
                        popular: false,
                        time: "25min",
                        image: "https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/D-K623.jpg?ver=39.7",
                    },
                    {
                        id: "kfc6",
                        name: "Veg Biryani Bucket",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "199",
                        food_type: "Biryani",
                        popular: true,
                        time: "20min",
                        image: "https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/D-K622.jpg?ver=39.7",
                    },
                ]
            },
            {
                title: "Burgers",
                food_items: [
                    {
                        id: "kfc7",
                        name: "2 Chicken Krisper Burgers",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "248",
                        food_type: "Burger",
                        popular: false,
                        time: "25min",
                        image: "https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/D-PR00001025.jpg?ver=39.7",
                    },
                    {
                        id: "kfc8",
                        name: "Tandoori Zinger Burger",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "208",
                        food_type: "Burger",
                        popular: true,
                        time: "20min",
                        image: "https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/D-K540.jpg?ver=39.7",
                    },
                    {
                        id: "kfc9",
                        name: "Veg Zinger Burger",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "188",
                        food_type: "Burger",
                        popular: false,
                        time: "25min",
                        image: "https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/D-K146.jpg?ver=39.7",
                    },
                    {
                        id: "kfc10",
                        name: "2 Veg Krispers Meal",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "288",
                        food_type: "Burger",
                        popular: true,
                        time: "20min",
                        image: "https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/items/xl/D-PR00001023.jpg?ver=39.7",
                    },
                ]
            },
        ]
    },
    {
        id: 6,
        name: "Coffee Cultuer",
        image: "https://nikunjsonigara.github.io/Food-Delivery-App-PT/image/Ellipse%205.png",
        description: "Pizza, Fast Food, Beverages",
        address: "Vesu, Surat",
        time: "11am - 11pm",
        average_cost: "700rs per 2 person",
        location: "https://www.google.com/maps/place/La+Pino'z+Pizza/@21.1475147,72.7628954,17z/data=!3m2!4b1!5s0x3be04d877f31bd7f:0x8538a10f9c5dfdc9!4m6!3m5!1s0x3be04d877a1c6bb5:0x94d7f84db7ecdc60!8m2!3d21.1475097!4d72.7654703!16s%2Fg%2F11fylw5mmw?entry=ttu",
        menu: [
            {
                menu_id: 1,
                menu_name: "dinning menu",
                menu_image: "https://cheatdaydesign.com/wp-content/uploads/2023/04/Chipotle-Menu-Nutrition.png.webp",
            },
            {
                menu_id: 2,
                menu_name: "takeaway menu",
                menu_image: "https://cheatdaydesign.com/wp-content/uploads/2023/04/Chipotle-Lifestyle-Bowls.png",
            },
        ],
        food: [
            {
                title: "Recommended",
                food_items: [
                    {
                        id: "lp1",
                        name: "Margherita Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "140",
                        food_type: "Pizza",
                        popular: true,
                        time: "20min",
                        image: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?q=80&w=2235&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp4",
                        name: "Double Cheese Margherita Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "150",
                        food_type: "Pizza",
                        popular: true,
                        time: "20min",
                        image: "https://images.unsplash.com/photo-1571066811602-716837d681de?q=80&w=1844&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp6",
                        name: "Garden Delight Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "180",
                        food_type: "Pizza",
                        popular: true,
                        time: "20min",
                        image: "https://images.unsplash.com/photo-1593504049359-74330189a345?q=80&w=2127&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp7",
                        name: "Lovers Bite Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "200",
                        food_type: "Pizza",
                        popular: true,
                        time: "20min",
                        image: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?q=80&w=2340&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                ]
            },
            {
                title: "Pizzas",
                food_items: [
                    {
                        id: "lp1",
                        name: "Margherita Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "140",
                        food_type: "Pizza",
                        popular: true,
                        time: "20min",
                        image: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?q=80&w=2235&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp2",
                        name: "Brick Oven Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "150",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?q=80&w=2188&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp3",
                        name: "Italian Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "130",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1544982503-9f984c14501a?q=80&w=2187&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp4",
                        name: "Double Cheese Margherita Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "150",
                        food_type: "Pizza",
                        popular: true,
                        time: "20min",
                        image: "https://images.unsplash.com/photo-1571066811602-716837d681de?q=80&w=1844&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp5",
                        name: "Neapolitan Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "160",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1593246049226-ded77bf90326?q=80&w=2235&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp6",
                        name: "Garden Delight Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "180",
                        food_type: "Pizza",
                        popular: true,
                        time: "20min",
                        image: "https://images.unsplash.com/photo-1593504049359-74330189a345?q=80&w=2127&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp7",
                        name: "Lovers Bite Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "200",
                        food_type: "Pizza",
                        popular: true,
                        time: "20min",
                        image: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?q=80&w=2340&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp8",
                        name: "Sicilian Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "210",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1581873372796-635b67ca2008?q=80&w=2340&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp9",
                        name: "New York Style Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "220",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1552539618-7eec9b4d1796?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MjV8fHxlbnwwfHx8fHw%3D",
                    },
                    {
                        id: "lp10",
                        name: "California Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "250",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1595708684082-a173bb3a06c5?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8Mjh8fHxlbnwwfHx8fHw%3D",
                    },
                    {
                        id: "lp11",
                        name: "Greek Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "300",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=2338&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                ]
            },
            {
                title: "Classic Pizzas For Classic Maniacs",
                food_items: [
                    {
                        id: "lp2",
                        name: "Brick Oven Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "150",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?q=80&w=2188&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp4",
                        name: "Double Cheese Margherita Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "150",
                        food_type: "Pizza",
                        popular: true,
                        time: "20min",
                        image: "https://images.unsplash.com/photo-1571066811602-716837d681de?q=80&w=1844&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp5",
                        name: "Neapolitan Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "160",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1593246049226-ded77bf90326?q=80&w=2235&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp7",
                        name: "Lovers Bite Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "200",
                        food_type: "Pizza",
                        popular: true,
                        time: "20min",
                        image: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?q=80&w=2340&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp9",
                        name: "New York Style Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "220",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1552539618-7eec9b4d1796?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MjV8fHxlbnwwfHx8fHw%3D",
                    },
                    {
                        id: "lp10",
                        name: "California Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "250",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1595708684082-a173bb3a06c5?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8Mjh8fHxlbnwwfHx8fHw%3D",
                    },
                    {
                        id: "lp11",
                        name: "Greek Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "300",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=2338&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                ]
            },
            {
                title: "Garlic Breads",
                food_items: [
                    {
                        id: "lp2",
                        name: "Brick Oven Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "150",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?q=80&w=2188&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp5",
                        name: "Neapolitan Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "160",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1593246049226-ded77bf90326?q=80&w=2235&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp9",
                        name: "New York Style Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "220",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1552539618-7eec9b4d1796?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MjV8fHxlbnwwfHx8fHw%3D",
                    },
                    {
                        id: "lp11",
                        name: "Greek Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "300",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=2338&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                ]
            },
            {
                title: "Lasagna",
                food_items: [
                    {
                        id: "lp2",
                        name: "Brick Oven Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "150",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?q=80&w=2188&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp9",
                        name: "New York Style Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "220",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1552539618-7eec9b4d1796?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MjV8fHxlbnwwfHx8fHw%3D",
                    },
                    {
                        id: "lp11",
                        name: "Greek Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "300",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=2338&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                ]
            },
            {
                title: "Desserts",
                food_items: [
                    {
                        id: "lp5",
                        name: "Neapolitan Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "160",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1593246049226-ded77bf90326?q=80&w=2235&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                    {
                        id: "lp11",
                        name: "Greek Pizza",
                        description: "A Classic Cheesy Margharita. Can't Go Wrong.",
                        price: "300",
                        food_type: "Pizza",
                        popular: false,
                        time: "25min",
                        image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=2338&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    },
                ]
            }
        ]
    }
]
